# Generated by Django 2.2.12 on 2020-05-07 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        ('members', '0002_auto_20200507_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentlyComplexLis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complex_ins', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.ComplexInformation', verbose_name='단지정보')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='유저')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='complexs',
            field=models.ManyToManyField(through='members.RecentlyComplexLis', to='posts.ComplexInformation'),
        ),
    ]
