# Generated by Django 2.2.12 on 2020-06-14 15:34

from django.db import migrations, models
import django.db.models.deletion
import presales.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=True, max_length=30, verbose_name='브랜드 명')),
            ],
        ),
        migrations.CreateModel(
            name='PreSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10, verbose_name='분양 예정')),
                ('term', models.CharField(max_length=30, verbose_name='모집 공고')),
                ('name', models.CharField(max_length=40, verbose_name='단지 명')),
                ('place', models.CharField(max_length=25, verbose_name='장소')),
                ('salesType', models.CharField(max_length=10, verbose_name='판매 유형')),
                ('salesPrice', models.CharField(max_length=40, verbose_name='분양 가격')),
                ('totalCitizen', models.CharField(max_length=20, verbose_name='총 세대수')),
                ('salesCitizen', models.CharField(max_length=20, verbose_name='분양 세대 수')),
                ('minMaxFloor', models.CharField(max_length=40, verbose_name='최저-최고 층')),
                ('complexScale', models.CharField(max_length=10, verbose_name='단지 규모')),
                ('detailType', models.CharField(max_length=10, verbose_name='건물 유형')),
                ('constraint', models.CharField(max_length=15, verbose_name='전매 가능 여부')),
                ('area', models.CharField(max_length=30, verbose_name='전용 면적')),
                ('supplyType', models.CharField(max_length=10, verbose_name='공급 유형')),
                ('constraintArea', models.CharField(max_length=10, verbose_name='규제 지역')),
                ('recruit', models.CharField(max_length=20, verbose_name='모집 공고일')),
                ('builder', models.CharField(max_length=20, verbose_name='건설사')),
                ('maxPrice', models.CharField(max_length=10, verbose_name='분양가 상한제')),
                ('moveIn', models.CharField(max_length=20, verbose_name='입주 예정일')),
                ('developer', models.CharField(max_length=40, verbose_name='시행사')),
                ('constraintTerm', models.CharField(max_length=40, verbose_name='규제 기간')),
                ('detailPrice', models.CharField(max_length=20, null=True, verbose_name='분양가')),
                ('pricePyeong', models.CharField(max_length=20, null=True, verbose_name='평당가')),
                ('averPrice', models.CharField(max_length=50, null=True, verbose_name='지역 평균가')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='presales.Brand')),
            ],
        ),
        migrations.CreateModel(
            name='Thema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=True, max_length=30, verbose_name='테마 명')),
            ],
        ),
        migrations.CreateModel(
            name='PreSaleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=presales.models.presales_image_path, verbose_name='분양 이미지')),
                ('presale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presales.PreSale')),
            ],
        ),
        migrations.AddField(
            model_name='presale',
            name='thema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='presales.Thema'),
        ),
    ]
