# Generated by Django 2.2.12 on 2020-05-10 03:47

from django.db import migrations, models
import presales.models


class Migration(migrations.Migration):

    dependencies = [
        ('presales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presaleimage',
            name='image',
            field=models.ImageField(null=True, upload_to=presales.models.presales_image_path, verbose_name='분양 이미지'),
        ),
    ]
