# Generated by Django 2.2.12 on 2020-05-08 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='브랜드 명')),
            ],
        ),
        migrations.AlterField(
            model_name='presale',
            name='thema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='presales.Thema'),
        ),
        migrations.AddField(
            model_name='presale',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='presales.Brand'),
        ),
    ]
