# Generated by Django 2.2.12 on 2020-05-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(default=True, max_length=30, verbose_name='브랜드 명'),
        ),
        migrations.AlterField(
            model_name='thema',
            name='name',
            field=models.CharField(default=True, max_length=30, verbose_name='테마 명'),
        ),
    ]
