# Generated by Django 2.2.12 on 2020-06-03 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200603_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postroom',
            name='distance',
        ),
    ]
