# Generated by Django 2.2.12 on 2020-05-06 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200506_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancefee',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.AdministrativeDetail', verbose_name='포함 항목'),
        ),
        migrations.AlterField(
            model_name='maintenancefee',
            name='totalFee',
            field=models.FloatField(null=True, verbose_name='관리비 합계'),
        ),
    ]
