# Generated by Django 2.2.12 on 2020-05-06 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200506_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postroom',
            name='description',
            field=models.TextField(max_length=500, null=True, verbose_name='설명'),
        ),
        migrations.AlterField(
            model_name='postroom',
            name='heatingType',
            field=models.CharField(max_length=10, null=True, verbose_name='난방 종류'),
        ),
        migrations.AlterField(
            model_name='postroom',
            name='supplyAreaInt',
            field=models.IntegerField(null=True, verbose_name='정수형 공급 면적'),
        ),
    ]
