# Generated by Django 2.2.12 on 2020-05-06 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200506_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postroom',
            name='description',
            field=models.TextField(max_length=1000, null=True, verbose_name='설명'),
        ),
    ]
