# Generated by Django 2.2.12 on 2020-05-06 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20200506_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postroom',
            name='moveInDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='입주 가능 날짜'),
        ),
        migrations.AlterField(
            model_name='postroom',
            name='parkingDetail',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='주차 비용'),
        ),
        migrations.AlterField(
            model_name='postroom',
            name='parkingPay',
            field=models.FloatField(blank=True, null=True, verbose_name='주차 비용'),
        ),
    ]
